crop_info = {
        'rice': 'Based upon our data of thousands of farming samples, the best farming conditions for rice are:<br><br>'
                ' N range -> 60 - 99<br>'
                ' P range -> 35 - 60<br>'
                ' K range -> 35 -45<br>'
                ' Temperature -> 20 - 27<br>'
                ' Humidity -> 80 - 85<br>'
                ' pH -> 5 - 7.8<br>'
                ' Rainfall -> 182 -> 298<br><br>'
                ' Since your values fit all these parameters, this crop is best suitable for your soil!',
        'maize': 'Based upon our data of thousands of farming samples, the best farming conditions for maize are:<br><br>'
                ' N range -> 60 - 100<br>'
                ' P range -> 35 - 60<br>'
                ' K range -> 15 - 25<br>'
                ' Temperature -> 20 - 27<br>'
                ' Humidity -> 55 -75<br>'
                ' pH -> 5.5 - 7<br>'
                ' Rainfall -> 60 -109<br><br>'
                ' Since your values fit all these parameters, this crop is best suitable for your soil!',
        'chickpea': 'Based upon our data of thousands of farming samples, the best farming conditions for chickpea are:<br><br>'
                ' N range -> 20 -60<br>'
                ' P range -> 55 - 80<br>'
                ' K range -> 75 -85<br>'
                ' Temperature -> 17 -21<br>'
                ' Humidity -> 14 - 20<br>'
                ' pH -> 6 - 8.8<br>'
                ' Rainfall -> 65 -94<br><br>'
                ' Since your values fit all these parameters, this crop is best suitable for your soil!',
        'kidneybeans': 'Based upon our data of thousands of farming samples, the best farming conditions for kidneybeans are:<br><br>'
                ' N range<br>'
                ' P range<br>'
                ' K range<br>'
                ' Temperature<br>'
                ' Humidity<br>'
                ' pH<br>'
                ' Rainfall.<br><br>'
                ' Since your values fit all these parameters, this crop is best suitable for your soil!',
        'pigeonpeas': 'Based upon our data of thousands of farming samples, the best farming conditions for pigeonpeas are:<br>'
                ' N range<br>'
                ' P range<br>'
                ' K range<br>'
                ' Temperature<br>'
                ' Humidity<br>'
                ' pH<br>'
                ' Rainfall.'
                ' Since your values fit all these parameters, this crop is best suitable for your soil!',
        'mothbeans': 'Based upon our data of thousands of farming samples, the best farming conditions for mothbeans are:<br>'
                ' N range<br>'
                ' P range<br>'
                ' K range<br>'
                ' Temperature<br>'
                ' Humidity<br>'
                ' pH<br>'
                ' Rainfall.'
                ' Since your values fit all these parameters, this crop is best suitable for your soil!',
        'mungbean': 'Based upon our data of thousands of farming samples, the best farming conditions for mungbean are:<br>'
                ' N range<br>'
                ' P range<br>'
                ' K range<br>'
                ' Temperature<br>'
                ' Humidity<br>'
                ' pH<br>'
                ' Rainfall.'
                ' Since your values fit all these parameters, this crop is best suitable for your soil!',
        'blackgram': 'Based upon our data of thousands of farming samples, the best farming conditions for blackgram are:<br>'
                ' N range<br>'
                ' P range<br>'
                ' K range<br>'
                ' Temperature<br>'
                ' Humidity<br>'
                ' pH<br>'
                ' Rainfall.'
                ' Since your values fit all these parameters, this crop is best suitable for your soil!',
        'lentil': 'Based upon our data of thousands of farming samples, the best farming conditions for lentil are:<br>'
                ' N range<br>'
                ' P range<br>'
                ' K range<br>'
                ' Temperature<br>'
                ' Humidity<br>'
                ' pH<br>'
                ' Rainfall.'
                ' Since your values fit all these parameters, this crop is best suitable for your soil!',
        'pomegranate': 'Based upon our data of thousands of farming samples, the best farming conditions for pomegranate are:<br>'
                ' N range<br>'
                ' P range<br>'
                ' K range<br>'
                ' Temperature<br>'
                ' Humidity<br>'
                ' pH<br>'
                ' Rainfall.'
                ' Since your values fit all these parameters, this crop is best suitable for your soil!',
        'banana':'Based upon our data of thousands of farming samples, the best farming conditions for banana are:<br>'
                ' N range<br>'
                ' P range<br>'
                ' K range<br>'
                ' Temperature<br>'
                ' Humidity<br>'
                ' pH<br>'
                ' Rainfall.'
                ' Since your values fit all these parameters, this crop is best suitable for your soil!',
        'mango':'Based upon our data of thousands of farming samples, the best farming conditions for mango are:<br>'
                ' N range<br>'
                ' P range<br>'
                ' K range<br>'
                ' Temperature<br>'
                ' Humidity<br>'
                ' pH<br>'
                ' Rainfall.'
                ' Since your values fit all these parameters, this crop is best suitable for your soil!',
        'grapes': 'Based upon our data of thousands of farming samples, the best farming conditions for grapes are:<br>'
                ' N range<br>'
                ' P range<br>'
                ' K range<br>'
                ' Temperature<br>'
                ' Humidity<br>'
                ' pH<br>'
                ' Rainfall.'
                ' Since your values fit all these parameters, this crop is best suitable for your soil!',
        'watermelon': 'Based upon our data of thousands of farming samples, the best farming conditions for watermelon are:<br>'
                ' N range<br>'
                ' P range<br>'
                ' K range<br>'
                ' Temperature<br>'
                ' Humidity<br>'
                ' pH<br>'
                ' Rainfall.'
                ' Since your values fit all these parameters, this crop is best suitable for your soil!',
        'muskmelon': 'Based upon our data of thousands of farming samples, the best farming conditions for muskmelon are:<br>'
                ' N range<br>'
                ' P range<br>'
                ' K range<br>'
                ' Temperature<br>'
                ' Humidity<br>'
                ' pH<br>'
                ' Rainfall.'
                ' Since your values fit all these parameters, this crop is best suitable for your soil!',
        'apple': 'Based upon our data of thousands of farming samples, the best farming conditions for apple are:<br>'
                ' N range<br>'
                ' P range<br>'
                ' K range<br>'
                ' Temperature<br>'
                ' Humidity<br>'
                ' pH<br>'
                ' Rainfall.'
                ' Since your values fit all these parameters, this crop is best suitable for your soil!',
        'orange': 'Based upon our data of thousands of farming samples, the best farming conditions for orange are:<br>'
                ' N range<br>'
                ' P range<br>'
                ' K range<br>'
                ' Temperature<br>'
                ' Humidity<br>'
                ' pH<br>'
                ' Rainfall.'
                ' Since your values fit all these parameters, this crop is best suitable for your soil!',
        'papaya': 'Based upon our data of thousands of farming samples, the best farming conditions for papaya are:<br>'
                ' N range<br>'
                ' P range<br>'
                ' K range<br>'
                ' Temperature<br>'
                ' Humidity<br>'
                ' pH<br>'
                ' Rainfall.'
                ' Since your values fit all these parameters, this crop is best suitable for your soil!',
        'coconut': 'Based upon our data of thousands of farming samples, the best farming conditions for coconut are:<br>'
                ' N range<br>'
                ' P range<br>'
                ' K range<br>'
                ' Temperature<br>'
                ' Humidity<br>'
                ' pH<br>'
                ' Rainfall.'
                ' Since your values fit all these parameters, this crop is best suitable for your soil!',
        'cotton': 'Based upon our data of thousands of farming samples, the best farming conditions for cotton are:<br><br>'
                ' N range -> 100 - 140<br>'
                ' P range -> 35 - 60<br>'
                ' K range -> 15 - 25<br>'
                ' Temperature -> 22 - 26<br>'
                ' Humidity -> 75 - 84.8<br>'
                ' pH -> 5.8 - 8<br>'
                ' Rainfall -> 60 -99<br><br>'
                ' Since your values fit all these parameters, this crop is best suitable for your soil!',
        'jute': 'Based upon our data of thousands of farming samples, the best farming conditions for jute are:<br><br>'
                ' N range -> 60 - 100<br>'
                ' P range -> 35 - 60<br>'
                ' K range -> 35 - 45<br>'
                ' Temperature -> 23 - 27<br>'
                ' Humidity -> 70 - 90<br>'
                ' pH -> 6 - 7.5<br>'
                ' Rainfall -> 150 - 199<br><br>'
                ' Since your values fit all these parameters, this crop is best suitable for your soil!',
        'coffee': 'Based upon our data of thousands of farming samples, the best farming conditions for coffee are:<br><br>'
                ' N range -> 80 - 99<br>'
                ' P range -> 15 - 40<br>'
                ' K range -> 25 - 35<br>'
                ' Temperature -> 23 - 28<br>'
                ' Humidity -> 50 - 70<br>'
                ' pH -> 6 - 7.5<br>'
                ' Rainfall -> 115 - 199<br><br>'
                ' Since your values fit all these parameters, this crop is best suitable for your soil!',
        # Add more crop options here
    }